"""create points and recruiting tables

Revision ID: 7012942d44f5
Revises: 
Create Date: 2026-07-12 12:41:13.678019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7012942d44f5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('company_normalized', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('domains', sa.JSON(), nullable=True),
    sa.Column('min_match_threshold', sa.Integer(), server_default=sa.text('(75)'), nullable=False),
    sa.Column('is_opted_in', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('source_row_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_row_id')
    )
    op.create_index(op.f('ix_employees_company_normalized'), 'employees', ['company_normalized'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('license_key_hash', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('gmail_refresh_token_enc', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_license_key_hash'), 'users', ['license_key_hash'], unique=True)
    op.create_table('points_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.Enum('RECRUITER_ADDED_NEW', 'RECRUITER_ENRICHED', 'EMAIL_SENT', 'REFERRAL_REQUESTED', 'REFERRAL_REFUND', 'ADMIN_ADJUSTMENT', name='actiontype', native_enum=False, length=32), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('ref_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_points_ledger_ref_id'), 'points_ledger', ['ref_id'], unique=False)
    op.create_index(op.f('ix_points_ledger_user_id'), 'points_ledger', ['user_id'], unique=False)
    op.create_table('recruiters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('company_normalized', sa.String(length=255), nullable=False),
    sa.Column('added_by_user_id', sa.Integer(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['added_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_recruiters_company_normalized', 'recruiters', ['company_normalized'], unique=False)
    op.create_table('referral_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('job_url_hash', sa.String(length=32), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('match_score', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', 'EXPIRED', name='referralstatus', native_enum=False, length=16), server_default='pending', nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('points_charged', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('send_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recruiter_id', sa.Integer(), nullable=False),
    sa.Column('job_url_hash', sa.String(length=32), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('SENT', 'FAILED', name='sendstatus', native_enum=False, length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['recruiter_id'], ['recruiters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_send_log_user_recruiter_job_sent', 'send_log', ['user_id', 'recruiter_id', 'job_url_hash'], unique=True, sqlite_where=sa.text("status = 'sent'"), postgresql_where=sa.text("status = 'sent'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_send_log_user_recruiter_job_sent', table_name='send_log', sqlite_where=sa.text("status = 'sent'"), postgresql_where=sa.text("status = 'sent'"))
    op.drop_table('send_log')
    op.drop_table('referral_requests')
    op.drop_index('ix_recruiters_company_normalized', table_name='recruiters')
    op.drop_table('recruiters')
    op.drop_index(op.f('ix_points_ledger_user_id'), table_name='points_ledger')
    op.drop_index(op.f('ix_points_ledger_ref_id'), table_name='points_ledger')
    op.drop_table('points_ledger')
    op.drop_index(op.f('ix_users_license_key_hash'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_employees_company_normalized'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
